### ISSUE TITLE
powershell

### ISSUE THREAD

**Issue by howtoscriptinpython** [KraoESPfan1n/Loading-Screen-Bloxstrap#1]
![Знімок екрана 2024-08-23 105053](https://github.com/user-attachments/assets/6bd8223e-5502-4d86-8128-233e09a812f5)
how do i fix it

**Comment by hxll-f** [comment]
Did the logging screen ever show up?

![log](https://github.com/user-attachments/assets/0e4c95b9-feb1-495e-87b2-406d88099100)

**Comment by howtoscriptinpython** [comment]
> Did the logging screen ever show up?
> 
> ![log](https://private-user-images.githubusercontent.com/173039774/360841323-0e4c95b9-feb1-495e-87b2-406d88099100.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDAzODEsIm5iZiI6MTcyNDQwMDA4MSwicGF0aCI6Ii8xNzMwMzk3NzQvMzYwODQxMzIzLTBlNGM5NWI5LWZlYjEtNDk1ZS04N2IyLTQwNmQ4ODA5OTEwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QwODAxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTU0OWVjYjg0OWVlMDE0Y2Y0NzJiMGQzNWUxMDRlOTJjZTZkNjM5ZmJhMTUwYWIzZmFhZjg1NTM2MWZiNjIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cb6mbsZ5ejtRR2IHVPEIUP57aSjhRjpWAl453hUgou0)

yes

**Comment by hxll-f** [comment]
Could you please provide the log as well?

**Comment by howtoscriptinpython** [comment]
> Could you please provide the log as well?

![Знімок екрана 2024-08-23 104313](https://github.com/user-attachments/assets/1ba96bf8-bfde-4303-a187-9696a53eb93f)

**Comment by hxll-f** [comment]
Does the integration work / has it been added? (To check start Roblox / Open Bloxstrap Menu)

**Comment by howtoscriptinpython** [comment]
> Does the integration work / has it been added? (To check start Roblox / Open Bloxstrap Menu)

![image](https://github.com/user-attachments/assets/45291c6b-71e8-4ff7-9d0b-d1eb30c5d3ff)

**Comment by hxll-f** [comment]
You could try replacing the username with the actual username used on your User (e.g. "Тимофіи") to check if that works.

**Comment by howtoscriptinpython** [comment]
> You could try replacing the username with the actual username used on your User (e.g. "Тимофіи") to check if that works.

tysm

**Comment by hxll-f** [comment]
Ofcourse! For any other questions don't hesitate to open another ticket.
