### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by medemonhunter** [KraoESPfan1n/Loading-Screen-Bloxstrap#2]
### Python Script Bug Report

**Description**
It gives an error when trying to executing the "installer.py". The error? 
Traceback (most recent call last):
  File "C:\Users\Aurora\downloads\installer.py", line 101, in <module>
    if system_language.startswith("es"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'startswith'

**To Reproduce**
1. Open an terminal or cmd.
2. Do this command on where is the installer.py is located. like:
> cd C:\Users\Aurora\Downloads
> python installer.py

**Expected behavior**
It should launched the installer but it didn't.

**Screenshots**
![image](https://github.com/user-attachments/assets/694b45dc-501d-4881-9b9c-f0eb4b27fbdb)

**Specs Informations**
 - Windows 11
 - Python 3.12.6
 - Pillow 11.0.0

**Comment by KraoESPfan1n** [comment]
hmmm, let me fix it real quick

**Comment by KraoESPfan1n** [comment]
solved
dowload the installer again
